apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: wjarod/user-api
---
apiVersion: v1
kind: Service
metadata:
  name: user-clusterip-server
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-server-np
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 80
      targetPort: 80